// MIT

// WARNING: This file has automatically been generated on Sun, 27 Oct 2019 10:37:40 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../../ckb_ffi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

