// MIT

// WARNING: This file has automatically been generated on Thu, 24 Oct 2019 15:00:44 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../ckb_ffi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

