// MIT

// WARNING: This file has automatically been generated on Thu, 24 Oct 2019 15:22:37 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package types

/*
#cgo LDFLAGS: -static -L${SRCDIR}/../ -lckb_ffi -lpthread -ldl
#include "../ckb_ffi.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// OK as defined in ckb-types-go/ckb_ffi.h:14
	OK = 0x00
	// INVALID_JSON as defined in ckb-types-go/ckb_ffi.h:15
	INVALID_JSON = 0x01
	// INVALID_MOLECULE as defined in ckb-types-go/ckb_ffi.h:16
	INVALID_MOLECULE = 0x02
	// UNSUPPORTED_TYPE as defined in ckb-types-go/ckb_ffi.h:17
	UNSUPPORTED_TYPE = 0x03
)
